// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uymiloiscknpomhqtode.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bWlsb2lzY2tucG9taHF0b2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzcwNDcsImV4cCI6MjA2ODUxMzA0N30.ZBHreTlCYLFFNwk0Fc3jyw40VZN7osj4i8-LZBcgLhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});